Feature/src and other mods
boldlink/terraform-aws-elb pull request #2
Opened 2022-04-26 09:00 UTC by patrickmukumbu

In this PR I have included the following changes:
- Changed module source to point to tf registry
- Made some modification in the `load_balancer_policy resource` to be able to add multiple policies
- Used one example without access logs enabled
- Used one example with access logs enabled
- Added policy document for the s3 bucket defining permissions given to load balancer

2022-04-29 11:12 UTC, hugoalmeida264 requested changes

2022-04-29 11:12 UTC, hugoalmeida264 commented on data.tf
> +      "${join("", aws_s3_bucket.access_logs.*.arn)}/*",
Why are you using a join here? usually, this is used when you are pulling two values, but you can use `${value}${value}` instead

2022-04-29 11:12 UTC, hugoalmeida264 commented on data.tf
> +      identifiers = ["${data.aws_elb_service_account.main.arn}"]
Use locals on all data sources

2022-05-27 20:35 UTC, mariomerco approved these changes
Tested this and is pretty solid!

2022-05-30 10:42 UTC, hugoalmeida264 approved these changes

2022-05-30 10:42 UTC, merged